---
title: My Flashback of 2024
subtitle: "It might be a long monologue, so beware!"
date: 01.05.2025
categories: [philosophy]
---

Last year that is 2024 was so many things together. It was very complicated with extreme emotional turmoils. But overall the year was much like a teacher to me. I learned many new things about me and I observed my life in a different way. I became alcohol addicted or maybe consuming alcohol. I am not sure because an addict cannot say whether he is a addict or not. And on the contrary an addict is also unsure about his addiction. Anyways the thing is I was drinking too much. So, when I did not listen to my body, my body made me stop and send me to the hospital. I was scared and lonely that night. Even I was accompanied by Charlotte's mother, I was feeling extremely sad. I would always be indebted to Charlotte and her family for the support they have given me on that harsh time. I was crying at sudden times. I was not liking anything. Even anyone's smile making me irritated. What has happened to me? I had no clue back then. but now I have it. It is depression and anxiety and feeling of dislike. I went to a doctor. I was advised by Charlotte to do sports. 3 km running every morning. I started walking at first and then I started combination of running and walking. And finally after 1.5 months I was running everyday 3 km.

This moment gave me a time to think about how I can actually achieve anything if I kept consistent. Ability might be a thing but consistency is the key. From that moment onward, my view towards my life completely changed. I realized I was chasing something else that I might not want. Every moment of life is I think is an experiment. An experiment to refine the next experiment. I realized that I was overthinking about finishing my PhD and its quality. While this was not my goal at all. My goal is to actually feel myself and my consciousness while I am alive. My goal is to know me rather than thinking that getting my Phd will give my identity. While I do not even have one. So I am trying to define myself with work. This feeling made me sure about the wrongs I was doing until now. I am running while I should have walked slowly and observed it. I got a feeling about what I like. I like people, I like to tell them stories. Now sometimes it can be fiction, sometimes something that I recently learnt or something that I have a good gut feeling for. But I do like to talk. So, I believe that I would like to teach people. Now this do not need to be necessarily in a classroom setup. It can be through my writings. So I think my feeble idea of writing a book might become a reality. Let's see what the new year brings to me. For now I am looking forward to Tanay and Rittika's wedding and my India trip with Charlotte. I would like to experience what I bring this new year to myself. The only promise that I want to do it to myself is that I would be honest with my actions rather than just doing it like a stone. Happy new year!