project:
  type: website
  output-dir: docs

website:
  title: "Raunak Farhaz"
  site-url: https://raunakfarhaz.com
  favicon: images/favicon.svg
  search: false
  page-footer: $\textcopyright$ Raunak Farhaz | Berlin 2026
  navbar:
    title: false
    logo: images/favicon.svg
    left:
      - icon: ""
      - href: index.qmd
    right:
      - text: "CV"
        href: "./data/cv.pdf"
      - text: "Research"
        href: resources/research.qmd
      - text: "Publications"
        href: resources/pubs.qmd
      - text: "Learn"
        href: resources/learn.qmd
      - text: "Blog"
        href: resources/blog.qmd
      - text: "Internal"
        href: resources/personal.qmd

format:
  html:
    theme:
        # - cosmo
        - styles.scss
    toc: true
    toc-location: right
    smooth-scroll: true
    code-line-numbers: true
    code-overflow: wrap
    highlight-style: kate
    code-copy: true
  
    

