project:
  type: website
  output-dir: docs

website:
  title: "Raunak Farhaz"
  favicon: images/favicon.png
  search: false
  page-footer: $\textcopyright$ made by Raunak Farhaz | Berlin, Germany 2023
  navbar:
    title: false
    logo: images/favicon.png
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        href: resources/research.qmd
      - href: publication.qmd
        text: Publications
      - text: "Teaching"
        href: resources/teach.qmd
      - text: "Blog"
        href: blog/blog.qmd
      - text: "CV"
        href: resources/cv.qmd
      

format:
  html:
    theme:
      light: [morph, light.scss]
      dark: [morph, dark.scss]
    # mainfont: roboto
    # fontcolor: "#11028d"
    # linkcolor: "#6757ec"
    # monofont: courier new
    # backgroundcolor: "#d6d2fd"
    css: styles.css
    toc: true
    code-fold: true
  
editor: visual
    

