---
title: "PDF images in typst"
subtitle: How to put images in PDF formats in typst?
date: 10.26.2025
categories: [coding-update]
---

Usually in the academic journals especially concerning computational chemistry or physical chemistry, Portable Document File (PDF) format is the choice for images in articles. I have been writing my Ph.D. thesis in these days using `Typst`. Those who are not familiar with it, it is a new programming language for typesetting. It can be seen as the alternative to $\LaTeX$. It compiles very fast and is not heavy and slow like $\LaTeX$. I learned it quite fast, it took me only 4 hours train journey to learn it. It should be clear by now that how low the learning curve is. And the better part is one does not need to wait 1 min to compile their large thesis. So I took the challenge to write my thesis in `Typst` which is not a common thing to do in our field as everyone is indoctrinated by $\LaTeX$. I had only one fear while starting to write - most of my graphs and plots generated during my Ph.D. time is all in PDF file format. Some of the scripts I even lost. But I thought - "no problem I will convert them into SVG". But then I found out that a development version of `Typst` is supporting the `PDF` file format as images. I used it and I was happy. But now I am even more happy to share you the news that `Typst` is supporting native `PDF` files as images in their latest release of 0.14. So more reasons to use `Typst` now. It is just as simple as the following syntax.

```typ
#figure(
    image("image_filename.pdf", width: 75%),
    caption: [Fancy Caption]
)
```

::: {.callout-warning}
One note for VSCode users is - try to use the pre-release version of tinymist extension otherwise it might raise an error of "image type not supported". I hope the tinymist team fixes it soon.
:::

Until then enjoy. And yes I am very happy that I took the decision of writing my Ph.D. thesis in `Typst` and not in $\LaTeX$. I enjoy so much seeing my writing being compiled almost with zero latency.
